QBShared = QBShared or {}

QBShared.Vehicles = {
    ['akuma'] = {
        ['name'] = 'akuma',
        ['brand'] = 'Dinka',
        ['model'] = 'akuma',
        ['price'] = 13000,
        ['category'] = 'Dinka',
        ['categoryLabel'] = 'Dinka',
        ['hash'] = `akuma`,
        ['shop'] = 'motoshop',
    },
	['lectro'] = {
        ['name'] = 'lectro',
        ['brand'] = 'Principe',
        ['model'] = 'lectro',
        ['price'] = 13000,
        ['category'] = 'Principe',
        ['categoryLabel'] = 'Principe',
        ['hash'] = `lectro`,
        ['shop'] = 'truck',
    },
	['buccaneer'] = {
        ['name'] = 'Buccaneer',
        ['brand'] = 'Albany',
        ['model'] = 'buccaneer',
        ['price'] = 13000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `buccaneer`,
        ['shop'] = 'luxury',
    },
    ['buccaneer2'] = {
        ['name'] = 'Buccaneer Lowrider',
        ['brand'] = 'Albany',
        ['model'] = 'buccaneer2',
        ['price'] = 20000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `buccaneer2`,
        ['shop'] = 'luxury',
    },
    ['lurcher'] = {
        ['name'] = 'Lurcher',
        ['brand'] = 'Albany',
        ['model'] = 'lurcher',
        ['price'] = 8000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `lurcher`,
        ['shop'] = 'luxury',
    },
    ['virgo'] = {
        ['name'] = 'Virgo',
        ['brand'] = 'Albany',
        ['model'] = 'virgo',
        ['price'] = 9000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `virgo`,
        ['shop'] = 'luxury',
    },
    ['emperor'] = {
        ['name'] = 'Emperor',
        ['brand'] = 'Albany',
        ['model'] = 'emperor',
        ['price'] = 12000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `emperor`,
        ['shop'] = 'luxury',
    },
    ['primo'] = {
        ['name'] = 'Primo',
        ['brand'] = 'Albany',
        ['model'] = 'primo',
        ['price'] = 12000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `primo`,
        ['shop'] = 'luxury',
    },
    ['primo2'] = {
        ['name'] = 'Primo Lowrider',
        ['brand'] = 'Albany',
        ['model'] = 'primo2',
        ['price'] = 7000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `primo2`,
        ['shop'] = 'luxury',
    },
    ['washington'] = {
        ['name'] = 'Washington',
        ['brand'] = 'Albany',
        ['model'] = 'washington',
        ['price'] = 5000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `washington`,
        ['shop'] = 'luxury',
    },
    ['alpha'] = {                           
        ['name'] = 'Alpha',
        ['brand'] = 'Albany',
        ['model'] = 'alpha',
        ['price'] = 80000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `alpha`,
        ['shop'] = 'luxury',
    },
    ['BTYPE2'] = {                            
        ['name'] = 'Fränken Stange',
        ['brand'] = 'Albany',
        ['model'] = 'BTYPE2',
        ['price'] = 80000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `BTYPE2`,
        ['shop'] = 'luxury',
    },
    ['BTYPE'] = {                           
        ['name'] = 'Roosevelt',
        ['brand'] = 'Albany',
        ['model'] = 'BTYPE',
        ['price'] = 80000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `BTYPE`,
        ['shop'] = 'luxury',
    },
    ['BTYPE3'] = {
        ['name'] = 'Roosevelt Valor',
        ['brand'] = 'Albany',
        ['model'] = 'BTYPE3',
        ['price'] = 3200,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `BTYPE3`,
        ['shop'] = 'luxury',
    },
    ['cavalcade'] = {
        ['name'] = 'Cavalcade Base',
        ['brand'] = 'Albany',
        ['model'] = 'cavalcade',
        ['price'] = 30000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `cavalcade`,
        ['shop'] = 'luxury',
    },
    ['cavalcade2'] = {
        ['name'] = 'Cavalcade Premium',
        ['brand'] = 'Albany',
        ['model'] = 'cavalcade2',
        ['price'] = 10000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `cavalcade2`,
        ['shop'] = 'luxury',
    },
    ['hermes'] = {
        ['name'] = 'Hermes',
        ['brand'] = 'Albany',
        ['model'] = 'hermes',
        ['price'] = 12000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `hermes`,
        ['shop'] = 'luxury',
    },
    ['vstr'] = {
        ['name'] = 'V-STR',
        ['brand'] = 'Albany',
        ['model'] = 'vstr',
        ['price'] = 9000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `vstr`,
        ['shop'] = 'luxury',
    },
    ['manana2'] = {
        ['name'] = 'Manana Lowrider',
        ['brand'] = 'Albany',
        ['model'] = 'manana2',
        ['price'] = 30000,
        ['category'] = 'Albany',
        ['categoryLabel'] = 'Albany',
        ['hash'] = `manana2`,
        ['shop'] = 'luxury',
    },
    ['elegy'] = {
        ['name'] = 'Elegy Retro',
        ['brand'] = 'Annis',
        ['model'] = 'elegy',
        ['price'] = 40000,
        ['category'] = 'Annis',
        ['categoryLabel'] = 'Annis',
        ['hash'] = `elegy`,
        ['shop'] = 'luxury',
    },
    ['elegy2'] = {
        ['name'] = 'Elegy RH8',
        ['brand'] = 'Annis',
        ['model'] = 'elegy2',
        ['price'] = 32500,
        ['category'] = 'Annis',
        ['categoryLabel'] = 'Annis',
        ['hash'] = `elegy2`,
        ['shop'] = 'luxury',
    },
    ['LE7B'] = {
        ['name'] = 'RE-7B',
        ['brand'] = 'Annis',
        ['model'] = 'LE7B',
        ['price'] = 31000,
        ['category'] = 'Annis',
        ['categoryLabel'] = 'Annis',
        ['hash'] = `LE7B`,
        ['shop'] = 'luxury',
    },
    ['savestra'] = {
        ['name'] = 'Savestra',
        ['brand'] = 'Annis',
        ['model'] = 'savestra',
        ['price'] = 37000,
        ['category'] = 'Annis',
        ['categoryLabel'] = 'Annis',
        ['hash'] = `savestra`,
        ['shop'] = 'luxury',
    },
    ['s80'] = {
        ['name'] = 'S80RR',
        ['brand'] = 'Annis',
        ['model'] = 's80',
        ['price'] = 19000,
        ['category'] = 'Annis',
        ['categoryLabel'] = 'Annis',
        ['hash'] = `s80`,
        ['shop'] = 'luxury',
    },
    ['hellion'] = {
        ['name'] = 'Hellion',
        ['brand'] = 'Annis',
        ['model'] = 'hellion',
        ['price'] = 22000,
        ['category'] = 'Annis',
        ['categoryLabel'] = 'Annis',
        ['hash'] = `hellion`,
        ['shop'] = 'luxury',
    },
    ['zr380'] = {
        ['name'] = 'ZR380',
        ['brand'] = 'Annis',
        ['model'] = 'zr380',
        ['price'] = 999999999,
        ['category'] = 'Annis',
        ['categoryLabel'] = 'Annis',
        ['hash'] = `zr380`,
        ['shop'] = 'luxury',
    },
    ['euros'] = {
        ['name'] = 'Euros',
        ['brand'] = 'Annis',
        ['model'] = 'euros',
        ['price'] = 30000,
        ['category'] = 'Annis',
        ['categoryLabel'] = 'Annis',
        ['hash'] = `euros`,
        ['shop'] = 'luxury',
    },
    ['zr350'] = {
        ['name'] = 'ZR350',
        ['brand'] = 'Annis',
        ['model'] = 'zr350',
        ['price'] = 33000,
        ['category'] = 'Annis',
        ['categoryLabel'] = 'Annis',
        ['hash'] = `zr350`,
        ['shop'] = 'luxury',
    },
    ['remus'] = {
        ['name'] = 'Remus',
        ['brand'] = 'Annis',
        ['model'] = 'remus',
        ['price'] = 27000,
        ['category'] = 'Annis',
        ['categoryLabel'] = 'Annis',
        ['hash'] = `remus`,
        ['shop'] = 'luxury',
    },
    ['r300'] = {
        ['name'] = '300R',
        ['brand'] = 'Annis',
        ['model'] = 'r300',
        ['price'] = 34000,
        ['category'] = 'Annis',
        ['categoryLabel'] = 'Annis',
        ['hash'] = `r300`,
        ['shop'] = 'luxury',
    },
    ['panto'] = {
        ['name'] = 'Panto',
        ['brand'] = 'Benefactor',
        ['model'] = 'panto',
        ['price'] = 22000,
        ['category'] = 'Benefactor',
        ['categoryLabel'] = 'Benefactor',
        ['hash'] = `panto`,
        ['shop'] = 'luxury',
    },
    ['dubsta3'] = {
        ['name'] = 'Dubsta 6x6',
        ['brand'] = 'Benefactor',
        ['model'] = 'dubsta3',
        ['price'] = 28000,
        ['category'] = 'Benefactor',
        ['categoryLabel'] = 'Benefactor',
        ['hash'] = `dubsta3`,
        ['shop'] = 'luxury',
    },
    ['glendale'] = {
        ['name'] = 'Glendale',
        ['brand'] = 'Benefactor',
        ['model'] = 'glendale',
        ['price'] = 149000,
        ['category'] = 'Benefactor',
        ['categoryLabel'] = 'Benefactor',
        ['hash'] = `glendale`,
        ['shop'] = 'luxury',
    },
    ['schafter2'] = {
        ['name'] = 'Schafter Base',
        ['brand'] = 'Benefactor',
        ['model'] = 'schafter2',
        ['price'] = 205000,
        ['category'] = 'Benefactor',
        ['categoryLabel'] = 'Benefactor',
        ['hash'] = `schafter2`,
        ['shop'] = 'luxury',
    },
    ['schafter3'] = {
        ['name'] = 'Schafter V12 Base',
        ['brand'] = 'Benefactor',
        ['model'] = 'schafter3',
        ['price'] = 1120000,
        ['category'] = 'Benefactor',
        ['categoryLabel'] = 'Benefactor',
        ['hash'] = `schafter3`,
        ['shop'] = 'luxury',
    },
    ['schafter4'] = {
        ['name'] = 'Schafter V12 Premium',
        ['brand'] = 'Benefactor',
        ['model'] = 'schafter4',
        ['price'] = 1350000,
        ['category'] = 'Benefactor',
        ['categoryLabel'] = 'Benefactor',
        ['hash'] = `schafter4`,
        ['shop'] = 'luxury',
    },
	['schafter5'] = {
        ['name'] = 'Schafter V12 Base Armored',
        ['brand'] = 'Benefactor',
        ['model'] = 'schafter5',
        ['price'] = 999999999,
        ['category'] = 'Benefactor',
        ['categoryLabel'] = 'Benefactor',
        ['hash'] = `schafter5`,
        ['shop'] = 'luxury',
    },
	['schafter6'] = {
        ['name'] = 'Schafter V12 Premium Armored',
        ['brand'] = 'Benefactor',
        ['model'] = 'schafter6',
        ['price'] = 999999999,
        ['category'] = 'Benefactor',
        ['categoryLabel'] = 'Benefactor',
        ['hash'] = `schafter6`,
        ['shop'] = 'luxury',
    },
    -------------------------
    ['1lowhd'] = {
        ['name'] = 'Silverado 2015 low',
        ['brand'] = 'Chevrolet',
        ['model'] = '1lowhd',
        ['price'] = 13000000,
        ['category'] = 'Chevrolet',
        ['categoryLabel'] = 'Chevrolet',
        ['hash'] = `1lowhd`,
        ['shop'] = 'pdm',
    },
    ['4runn'] = {
        ['name'] = '4runner 2015 TRDPRO',
        ['brand'] = 'Toyota',
        ['model'] = '4runn',
        ['price'] = 13000000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `4runn`,
        ['shop'] = 'pdm',
    },
    ['23tundra'] = {
        ['name'] = 'Tundra 2023 Limited',
        ['brand'] = 'Toyota',
        ['model'] = '23tundra',
        ['price'] = 13000000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `23tundra`,
        ['shop'] = 'pdm',
    },
    ['23tundrasr'] = {
        ['name'] = 'Tundra 2023 Base',
        ['brand'] = 'Toyota',
        ['model'] = '23tundrasr',
        ['price'] = 13000000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `23tundrasr`,
        ['shop'] = 'pdm',
    },
    ['23tundratrd'] = {
        ['name'] = 'Tundra 2023 TRDPRO',
        ['brand'] = 'Toyota',
        ['model'] = '23tundratrd',
        ['price'] = 13000000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `23tundratrd`,
        ['shop'] = 'pdm',
    },
    ['79MudRunner'] = {
        ['name'] = 'Land Cruiser 79 Series 2022',
        ['brand'] = 'Toyota',
        ['model'] = '79MudRunner',
        ['price'] = 13000000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `79MudRunner`,
        ['shop'] = 'pdm',
    },
    ['89runner'] = {
        ['name'] = '4Runner 1989',
        ['brand'] = 'Toyota',
        ['model'] = '89runner',
        ['price'] = 13000000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `89runner`,
        ['shop'] = 'pdm',
    },
    ['190asap'] = {
        ['name'] = '190E Asap 1987',
        ['brand'] = 'Mercedes',
        ['model'] = '190asap',
        ['price'] = 13000000,
        ['category'] = 'Mercedes',
        ['categoryLabel'] = 'Mercedes',
        ['hash'] = `190asap`,
        ['shop'] = 'pdm',
    },
    ['370driftmachine'] = {
        ['name'] = '370Z Nismo LW 2020',
        ['brand'] = 'Nissan',
        ['model'] = '370driftmachine',
        ['price'] = 13000000,
        ['category'] = 'Nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `370driftmachine`,
        ['shop'] = 'pdm',
    },
    ['510'] = {
        ['name'] = 'Datsun 510 1971',
        ['brand'] = 'Nissan',
        ['model'] = '510',
        ['price'] = 13000000,
        ['category'] = 'Nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `510`,
        ['shop'] = 'pdm',
    },
    ['a33maxima'] = {
        ['name'] = 'Maxima 2003',
        ['brand'] = 'Nissan',
        ['model'] = 'a33maxima',
        ['price'] = 13000000,
        ['category'] = 'Nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `a33maxima`,
        ['shop'] = 'pdm',
    },
    ['abhawk'] = {
        ['name'] = 'Cherokee Trackhawk 2019',
        ['brand'] = 'Jeep',
        ['model'] = 'abhawk',
        ['price'] = 22000000,
        ['category'] = 'Jeep',
        ['categoryLabel'] = 'Jeep',
        ['hash'] = `abhawk`,
        ['shop'] = 'pdm',
    },
    ['benze55'] = {
        ['name'] = 'E55 AMG 2004',
        ['brand'] = 'Mercedes',
        ['model'] = 'benze55',
        ['price'] = 13000000,
        ['category'] = 'Mercedes',
        ['categoryLabel'] = 'Mercedes',
        ['hash'] = `benze55`,
        ['shop'] = 'pdm',
    },
    ['brabusgt600'] = {
        ['name'] = 'Brabus GT600 2016',
        ['brand'] = 'Mercedes',
        ['model'] = 'brabusgt600',
        ['price'] = 13000000,
        ['category'] = 'Mercedes',
        ['categoryLabel'] = 'Mercedes',
        ['hash'] = `brabusgt600`,
        ['shop'] = 'pdm',
    },
    ['crit300'] = {
        ['name'] = 'is300 Swap 2001',
        ['brand'] = 'Lexus',
        ['model'] = 'crit300',
        ['price'] = 13000000,
        ['category'] = 'Lexus',
        ['categoryLabel'] = 'Lexus',
        ['hash'] = `crit300`,
        ['shop'] = 'pdm',
    },
    ['demonhawk'] = {
        ['name'] = 'Cherokee Trackhawk 2020',
        ['brand'] = 'Jeep',
        ['model'] = 'demonhawk',
        ['price'] = 22000000,
        ['category'] = 'Jeep',
        ['categoryLabel'] = 'Jeep',
        ['hash'] = `demonhawk`,
        ['shop'] = 'pdm',
    },
    ['e60'] = {
        ['name'] = 'M5 E60 2009',
        ['brand'] = 'BMW',
        ['model'] = 'e60',
        ['price'] = 13000000,
        ['category'] = 'BMW',
        ['categoryLabel'] = 'BMW',
        ['hash'] = `e60`,
        ['shop'] = 'pdm',
    },
    ['g240sx'] = {
        ['name'] = '240sx 1990',
        ['brand'] = 'Nissan',
        ['model'] = 'g240sx',
        ['price'] = 13000000,
        ['category'] = 'Nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `g240sx`,
        ['shop'] = 'pdm',
    },
    ['gcram1500'] = {
        ['name'] = 'Ram 1500 2020 low',
        ['brand'] = 'Dodge',
        ['model'] = 'gcram1500',
        ['price'] = 13000000,
        ['category'] = 'Dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = `gcram1500`,
        ['shop'] = 'pdm',
    },
    ['gfmagxxl'] = {
        ['name'] = 'Magnum Srt8 2020',
        ['brand'] = 'Dodge',
        ['model'] = 'gfmagxxl',
        ['price'] = 13000000,
        ['category'] = 'Dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = `gfmagxxl`,
        ['shop'] = 'pdm',
    },
    ['GODz22SEMATACO'] = {
        ['name'] = 'Tacoma TRDPRO 2022',
        ['brand'] = 'Toyota',
        ['model'] = 'GODz22SEMATACO',
        ['price'] = 13000000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `GODz22SEMATACO`,
        ['shop'] = 'pdm',
    },
    ['gtz34'] = {
        ['name'] = 'Skyline R34 gtz 2002',
        ['brand'] = 'Nissan',
        ['model'] = 'gtz34',
        ['price'] = 13000000,
        ['category'] = 'Nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `gtz34`,
        ['shop'] = 'pdm',
    },
    ['gxap3'] = {
        ['name'] = 'S2000 2009',
        ['brand'] = 'Honda',
        ['model'] = 'gxap3',
        ['price'] = 13000000,
        ['category'] = 'Honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = `gxap3`,
        ['shop'] = 'pdm',
    },
    ['is300'] = {
        ['name'] = 'is300 2001',
        ['brand'] = 'Lexus',
        ['model'] = 'is30000',
        ['price'] = 1300000,
        ['category'] = 'Lexus',
        ['categoryLabel'] = 'Lexus',
        ['hash'] = `is300`,
        ['shop'] = 'pdm',
    },
    ['KillerHwak'] = {
        ['name'] = 'Cherokee Trackhawk 2018',
        ['brand'] = 'Jeep',
        ['model'] = 'KillerHwak',
        ['price'] = 22000000,
        ['category'] = 'Jeep',
        ['categoryLabel'] = 'Jeep',
        ['hash'] = `KillerHwak`,
        ['shop'] = 'pdm',
    },
    ['lp570hycade'] = {
        ['name'] = 'Gallardo LP570 2012',
        ['brand'] = 'Lamborghini',
        ['model'] = 'lp570hycade',
        ['price'] = 1350000000,
        ['category'] = 'Lamborghini',
        ['categoryLabel'] = 'Lamborghini',
        ['hash'] = `lp570hycade`,
        ['shop'] = 'pdm',
    },
    ['mr2aw11'] = {
        ['name'] = 'MR2 1988',
        ['brand'] = 'Toyota',
        ['model'] = 'mr2aw11',
        ['price'] = 13000000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `mr2aw11`,
        ['shop'] = 'pdm',
    },
    ['owltundra23'] = {
        ['name'] = 'Tundra TRDPRO OWL 2023',
        ['brand'] = 'Toyota',
        ['model'] = 'owltundra23',
        ['price'] = 13000000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `owltundra23`,
        ['shop'] = 'pdm',
    },
    ['srtday20'] = {
        ['name'] = 'Charger srt Donk 2020',
        ['brand'] = 'Dodge',
        ['model'] = 'srtday20',
        ['price'] = 13000000,
        ['category'] = 'Dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = `srtday20`,
        ['shop'] = 'pdm',
    },
    ['titanhawk'] = {
        ['name'] = 'Cherokee Trackhawk 2017',
        ['brand'] = 'Jeep',
        ['model'] = 'titanhawk',
        ['price'] = 22000000,
        ['category'] = 'Jeep',
        ['categoryLabel'] = 'Jeep',
        ['hash'] = `titanhawk`,
        ['shop'] = 'pdm',
    },
    ['topfoil'] = {
        ['name'] = 'Lancer Evolution MR 2005',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'topfoil',
        ['price'] = 13000000,
        ['category'] = 'Mitsubishi',
        ['categoryLabel'] = 'Mitsubishi',
        ['hash'] = `topfoil`,
        ['shop'] = 'pdm',
    },
    ['ToyoLCruiserJ79'] = {
        ['name'] = 'Land Cruiser 79 Series 2021',
        ['brand'] = 'Toyota',
        ['model'] = 'ToyoLCruiserJ79',
        ['price'] = 1300000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `ToyoLCruiserJ79`,
        ['shop'] = 'pdm',
    },
    ['ttrd'] = {
        ['name'] = 'Tundra TRDPRO 2019',
        ['brand'] = 'Toyota',
        ['model'] = 'ttrd',
        ['price'] = 1300000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `ttrd`,
        ['shop'] = 'pdm',
    },
    ['we2'] = {
        ['name'] = 'Wheel Chair',
        ['brand'] = 'Medline',
        ['model'] = 'we2',
        ['price'] = 999999999,
        ['category'] = 'cycles',
        ['categoryLabel'] = 'Cycles',
        ['hash'] = `we2`,
        ['shop'] = 'pdm',
    },
    ['wrangler22'] = {
        ['name'] = 'Wrangler 2022',
        ['brand'] = 'Jeep',
        ['model'] = 'wrangler22',
        ['price'] = 1300000,
        ['category'] = 'Jeep',
        ['categoryLabel'] = 'Jeep',
        ['hash'] = `wrangler22`,
        ['shop'] = 'pdm',
    },
    ['02rsx'] = {
        ['name'] = 'RSX s 2002',
        ['brand'] = 'Acura',
        ['model'] = '02rsx',
        ['price'] = 13000000,
        ['category'] = 'Acura',
        ['categoryLabel'] = 'Acura',
        ['hash'] = `02rsx`,
        ['shop'] = 'pdm',
    },
    ['19raptor'] = {
        ['name'] = 'Raptor 2019',
        ['brand'] = 'Ford',
        ['model'] = '19raptor',
        ['price'] = 13000000,
        ['category'] = 'Ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = `19raptor`,
        ['shop'] = 'pdm',
    },
    ['21hilux4x4c'] = {
        ['name'] = 'Hilux 2021',
        ['brand'] = 'Toyota',
        ['model'] = '21hilux4x4c',
        ['price'] = 13000000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `21hilux4x4c`,
        ['shop'] = 'pdm',
    },
    ['22toyotacom'] = {
        ['name'] = 'Tacoma TRD Pro 2022',
        ['brand'] = 'Toyota',
        ['model'] = '22toyotacom',
        ['price'] = 1300000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `22toyotacom`,
        ['shop'] = 'pdm',
    },
    ['75series'] = {
        ['name'] = '75 Series 2020',
        ['brand'] = 'Toyota',
        ['model'] = '75series',
        ['price'] = 1300000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `75series`,
        ['shop'] = 'pdm',
    },
    ['aventador'] = {
        ['name'] = 'Aventador 2022',
        ['brand'] = 'Lamborghini',
        ['model'] = 'aventador',
        ['price'] = 13000000,
        ['category'] = 'Lamborghini',
        ['categoryLabel'] = 'Lamborghini',
        ['hash'] = `aventador`,
        ['shop'] = 'pdm',
    },
    ['bigote'] = {
        ['name'] = 'Civic EK vti 1995',
        ['brand'] = 'Honda',
        ['model'] = 'bigote',
        ['price'] = 1300000,
        ['category'] = 'Honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = `bigote`,
        ['shop'] = 'pdm',
    },
    ['bnr34'] = {
        ['name'] = 'GTR Skyline R34 2002',
        ['brand'] = 'Nissan',
        ['model'] = 'bnr34',
        ['price'] = 1300000,
        ['category'] = 'Nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `bnr34`,
        ['shop'] = 'pdm',
    },
    ['btsupra94'] = {
        ['name'] = 'Is that a SUPRA! 1994',
        ['brand'] = 'Toyota',
        ['model'] = 'btsupra94',
        ['price'] = 1300000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `btsupra94`,
        ['shop'] = 'pdm',
    },
    ['city85'] = {
        ['name'] = 'City Turbo ii 1985',
        ['brand'] = 'Honda',
        ['model'] = 'city85',
        ['price'] = 1300000,
        ['category'] = 'Honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = `city85`,
        ['shop'] = 'pdm',
    },
    ['civic'] = {
        ['name'] = 'Civic Si 1999',
        ['brand'] = 'Honda',
        ['model'] = 'civic',
        ['price'] = 1300000,
        ['category'] = 'Honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = `civic`,
        ['shop'] = 'pdm',
    },
    ['civicek9rb'] = {
        ['name'] = 'Civic Hatchback RocketBunny 1996',
        ['brand'] = 'Honda',
        ['model'] = 'civicek9rb',
        ['price'] = 1300000,
        ['category'] = 'Honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = `civicek9rb`,
        ['shop'] = 'pdm',
    },
    ['ef9'] = {
        ['name'] = 'Civic EF9 1996',
        ['brand'] = 'Honda',
        ['model'] = 'ef9',
        ['price'] = 1300000,
        ['category'] = 'Honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = `ef9`,
        ['shop'] = 'pdm',
    },
    ['eg6'] = {
        ['name'] = 'Civic EG6 1995',
        ['brand'] = 'Honda',
        ['model'] = 'eg6',
        ['price'] = 1300000,
        ['category'] = 'Honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = `eg6`,
        ['shop'] = 'pdm',
    },
    ['ej2'] = {
        ['name'] = 'Civic Ej2 1994',
        ['brand'] = 'Honda',
        ['model'] = 'ej2',
        ['price'] = 1300000,
        ['category'] = 'Honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = `ej2`,
        ['shop'] = 'pdm',
    },
	['fnfcivic'] = {
        ['name'] = 'Civic FNF Ej2 1994',
        ['brand'] = 'Honda',
        ['model'] = 'fnfcivic',
        ['price'] = 1300000,
        ['category'] = 'Honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = `fnfcivic`,
        ['shop'] = 'pdm',
    },
	['frr'] = {
        ['name'] = 'Ranger Raptor 2022',
        ['brand'] = 'Ford',
        ['model'] = 'frr',
        ['price'] = 1300000,
        ['category'] = 'Ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = `frr`,
        ['shop'] = 'pdm',
    },
	['g35'] = {
        ['name'] = 'G35 2004',
        ['brand'] = 'Infiniti',
        ['model'] = 'g35',
        ['price'] = 1300000,
        ['category'] = 'Infiniti',
        ['categoryLabel'] = 'Infiniti',
        ['hash'] = `g35`,
        ['shop'] = 'pdm',
    },
	['inf'] = {
        ['name'] = 'Q60 2022',
        ['brand'] = 'Infiniti',
        ['model'] = 'inf',
        ['price'] = 1300000,
        ['category'] = 'Infiniti',
        ['categoryLabel'] = 'Infiniti',
        ['hash'] = `inf`,
        ['shop'] = 'pdm',
    },
	['nismo20'] = {
        ['name'] = 'GTR Nismo 2020',
        ['brand'] = 'Nissan',
        ['model'] = 'nismo20',
        ['price'] = 1300000,
        ['category'] = 'Nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `nismo20`,
        ['shop'] = 'pdm',
    },
	['PAaccordrd2'] = {
        ['name'] = 'Accord Touring 2015',
        ['brand'] = 'Honda',
        ['model'] = 'PAaccordrd2',
        ['price'] = 1300000,
        ['category'] = 'Honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = `PAaccordrd2`,
        ['shop'] = 'pdm',
    },
	['q50'] = {
        ['name'] = 'Q50 2022',
        ['brand'] = 'Infiniti',
        ['model'] = 'q50',
        ['price'] = 1300000,
        ['category'] = 'Infiniti',
        ['categoryLabel'] = 'Infiniti',
        ['hash'] = `q50`,
        ['shop'] = 'pdm',
    },
	['q70'] = {
        ['name'] = 'Q70 2019',
        ['brand'] = 'Infiniti',
        ['model'] = 'q70',
        ['price'] = 1300000,
        ['category'] = 'Infiniti',
        ['categoryLabel'] = 'Infiniti',
        ['hash'] = `q70`,
        ['shop'] = 'pdm',
    },
	['qx80'] = {
        ['name'] = 'QX80 2019',
        ['brand'] = 'Infiniti',
        ['model'] = 'qx80',
        ['price'] = 1300000,
        ['category'] = 'Infiniti',
        ['categoryLabel'] = 'Infiniti',
        ['hash'] = `qx80`,
        ['shop'] = 'pdm',
    },
	['razerhycade34'] = {
        ['name'] = 'Skyline Hycade R34 2002',
        ['brand'] = 'Nissan',
        ['model'] = 'razerhycade34',
        ['price'] = 1300000,
        ['category'] = 'Nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `razerhycade34`,
        ['shop'] = 'pdm',
    },
	['s2k'] = {
        ['name'] = 'S2000 2008',
        ['brand'] = 'Honda',
        ['model'] = 's2k',
        ['price'] = 1300000,
        ['category'] = 'Honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = `s2k`,
        ['shop'] = 'pdm',
    },
	['s500'] = {
        ['name'] = 'S500 4Matic 2022',
        ['brand'] = 'Mercedes',
        ['model'] = 's500',
        ['price'] = 1300000,
        ['category'] = 'Mercedes',
        ['categoryLabel'] = 'Mercedes',
        ['hash'] = `s500`,
        ['shop'] = 'pdm',
    },
	['silvia3'] = {
        ['name'] = 'Silvia 1997',
        ['brand'] = 'Nissan',
        ['model'] = 'silvia3',
        ['price'] = 1300000,
        ['category'] = 'Nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `silvia3`,
        ['shop'] = 'pdm',
    },
	['tltypes'] = {
        ['name'] = 'TL TypeS 2007',
        ['brand'] = 'Acura',
        ['model'] = 'tltypes',
        ['price'] = 1300000,
        ['category'] = 'Acura',
        ['categoryLabel'] = 'Acura',
        ['hash'] = `tltypes`,
        ['shop'] = 'pdm',
    },
	['toyotaft'] = {
        ['name'] = 'Supra 2020',
        ['brand'] = 'Toyota',
        ['model'] = 'toyotaft',
        ['price'] = 1300000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `toyotaft`,
        ['shop'] = 'pdm',
    },
	['toysupmk4'] = {
        ['name'] = 'Supra 1993',
        ['name'] = 'Supra 1993',
        ['brand'] = 'Toyota',
        ['model'] = 'toysupmk4',
        ['price'] = 1300000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `toysupmk4`,
        ['shop'] = 'pdm',
    },
	['jaguarftype'] = {
        ['name'] = 'F-Type 2020',
        ['brand'] = 'Jaguar',
        ['model'] = 'jaguarftype',
        ['price'] = 1300000,
        ['category'] = 'Jaguar',
        ['categoryLabel'] = 'Jaguar',
        ['hash'] = `jaguarftype`,
        ['shop'] = 'pdm',
    },
	['project8'] = {
        ['name'] = 'XE 2019',
        ['brand'] = 'Jaguar',
        ['model'] = 'project8',
        ['price'] = 1300000,
        ['category'] = 'Jaguar',
        ['categoryLabel'] = 'Jaguar',
        ['hash'] = `project8`,
        ['shop'] = 'pdm',
    },
	['xkgt'] = {
        ['name'] = 'XY R-S GT 2015',
        ['brand'] = 'Jaguar',
        ['model'] = 'xkgt',
        ['price'] = 1300000,
        ['category'] = 'Jaguar',
        ['categoryLabel'] = 'Jaguar',
        ['hash'] = `xkgt`,
        ['shop'] = 'pdm',
    },
	['rcf'] = {
        ['name'] = 'RCF 2023',
        ['brand'] = 'Lexus',
        ['model'] = 'rcf',
        ['price'] = 1300000,
        ['category'] = 'Lexus',
        ['categoryLabel'] = 'Lexus',
        ['hash'] = `rcf`,
        ['shop'] = 'pdm',
    },
	['650slw'] = {
        ['name'] = '650S LW 2017',
        ['brand'] = 'McLaren',
        ['model'] = '650slw',
        ['price'] = 1300000,
        ['category'] = 'McLaren',
        ['categoryLabel'] = 'McLaren',
        ['hash'] = `650slw`,
        ['shop'] = 'pdm',
    },
	['720nlargo'] = {
        ['name'] = '720S N Largo 2020',
        ['brand'] = 'McLaren',
        ['model'] = '720nlargo',
        ['price'] = 1300000,
        ['category'] = 'McLaren',
        ['categoryLabel'] = 'McLaren',
        ['hash'] = `720nlargo`,
        ['shop'] = 'pdm',
    },
	['evo10'] = {
        ['name'] = 'Lancer Evolution10 FQ-400 2016',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'evo10',
        ['price'] = 1300000,
        ['category'] = 'Mitsubishi',
        ['categoryLabel'] = 'Mitsubishi',
        ['hash'] = `evo10`,
        ['shop'] = 'pdm',
    },
	['evolution'] = {
        ['name'] = 'Lancer Evolution10 2015',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'evolution',
        ['price'] = 1300000,
        ['category'] = 'Mitsubishi',
        ['categoryLabel'] = 'Mitsubishi',
        ['hash'] = `evolution`,
        ['shop'] = 'pdm',
    },
	['mitsugto'] = {
        ['name'] = '3000GT 1999',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'mitsugto',
        ['price'] = 1300000,
        ['category'] = 'Mitsubishi',
        ['categoryLabel'] = 'Mitsubishi',
        ['hash'] = `mitsugto`,
        ['shop'] = 'pdm',
    },
	['s15rb'] = {
        ['name'] = 'Silvia S15 RB 1997',
        ['brand'] = 'Nissan',
        ['model'] = 's15rb',
        ['price'] = 1300000,
        ['category'] = 'Nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `s15rb`,
        ['shop'] = 'pdm',
    },
	['911r'] = {
        ['name'] = '911 R 2016',
        ['brand'] = 'Porsche',
        ['model'] = '911r',
        ['price'] = 1300000,
        ['category'] = 'Porsche',
        ['categoryLabel'] = 'Porsche',
        ['hash'] = `911r`,
        ['shop'] = 'pdm',
    },
	['gt3rs'] = {
        ['name'] = '911 GT3 RS 2020',
        ['brand'] = 'Porsche',
        ['model'] = 'gt3rs',
        ['price'] = 1300000,
        ['category'] = 'Porsche',
        ['categoryLabel'] = 'Porsche',
        ['hash'] = `gt3rs`,
        ['shop'] = 'pdm',
    },
	['panamera17turbo'] = {
        ['name'] = 'Panamera Turbo 2017',
        ['brand'] = 'Porsche',
        ['model'] = 'panamera17turbo',
        ['price'] = 1300000,
        ['category'] = 'Porsche',
        ['categoryLabel'] = 'Porsche',
        ['hash'] = `panamera17turbo`,
        ['shop'] = 'pdm',
    },
	['brz'] = {
        ['name'] = 'BRZ Pandem 2020',
        ['brand'] = 'Subaru',
        ['model'] = 'brz',
        ['price'] = 1300000,
        ['category'] = 'Subaru',
        ['categoryLabel'] = 'Subaru',
        ['hash'] = `brz`,
        ['shop'] = 'pdm',
    },
	['a90pit'] = {
        ['name'] = 'Supra Pandem 2020',
        ['brand'] = 'Toyota',
        ['model'] = 'a90pit',
        ['price'] = 1300000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `a90pit`,
        ['shop'] = 'pdm',
    },
	['casup'] = {
        ['name'] = 'Is that a fucking Supra 2020',
        ['brand'] = 'Toyota',
        ['model'] = 'casup',
        ['price'] = 13000000,
        ['category'] = 'Toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `casup`,
        ['shop'] = 'pdm',
    },
	['aone'] = {
        ['name'] = 'One 77 2009',
        ['brand'] = 'AstonMartin',
        ['model'] = 'aone',
        ['price'] = 1300000,
        ['category'] = 'AstonMartin',
        ['categoryLabel'] = 'AstonMartin',
        ['hash'] = `aone`,
        ['shop'] = 'pdm',
    },
	['speedster'] = {
        ['name'] = 'Speedster 2021',
        ['brand'] = 'AstonMartin',
        ['model'] = 'speedster',
        ['price'] = 1300000,
        ['category'] = 'AstonMartin',
        ['categoryLabel'] = 'AstonMartin',
        ['hash'] = `speedster`,
        ['shop'] = 'pdm',
    },
	['victor'] = {
        ['name'] = 'Victor 2021',
        ['brand'] = 'AstonMartin',
        ['model'] = 'victor',
        ['price'] = 1300000,
        ['category'] = 'AstonMartin',
        ['categoryLabel'] = 'AstonMartin',
        ['hash'] = `victor`,
        ['shop'] = 'pdm',
    },
	['r8cabt'] = {
        ['name'] = 'R8 Quattro ABT 2020',
        ['brand'] = 'Audi',
        ['model'] = 'r8cabt',
        ['price'] = 1300000,
        ['category'] = 'Audi',
        ['categoryLabel'] = 'Audi',
        ['hash'] = `r8cabt`,
        ['shop'] = 'pdm',
    },
	['rs3lms'] = {
        ['name'] = 'RS3 LMS 2017',
        ['brand'] = 'Audi',
        ['model'] = 'rs3lms',
        ['price'] = 1300000,
        ['category'] = 'Audi',
        ['categoryLabel'] = 'Audi',
        ['hash'] = `rs3lms`,
        ['shop'] = 'pdm',
    },
	['m3gtr'] = {
        ['name'] = 'M3 GTR 2001',
        ['brand'] = 'BMW',
        ['model'] = 'm3gtr',
        ['price'] = 1300000,
        ['category'] = 'BMW',
        ['categoryLabel'] = 'BMW',
        ['hash'] = `m3gtr`,
        ['shop'] = 'pdm',
    },
	['mansm8'] = {
        ['name'] = 'M8 2022',
        ['brand'] = 'BMW',
        ['model'] = 'mansm8',
        ['price'] = 1300000,
        ['category'] = 'BMW',
        ['categoryLabel'] = 'BMW',
        ['hash'] = `mansm8`,
        ['shop'] = 'pdm',
    },
	['rmodm4gts'] = {
        ['name'] = 'M4 GTS 2016',
        ['brand'] = 'BMW',
        ['model'] = 'rmodm4gts',
        ['price'] = 1300000,
        ['category'] = 'BMW',
        ['categoryLabel'] = 'BMW',
        ['hash'] = `rmodm4gts`,
        ['shop'] = 'pdm',
    },
	['rmodmi8lb'] = {
        ['name'] = 'I8 EDrive LB 2020',
        ['brand'] = 'BMW',
        ['model'] = 'rmodmi8lb',
        ['price'] = 1300000,
        ['category'] = 'BMW',
        ['categoryLabel'] = 'BMW',
        ['hash'] = `rmodmi8lb`,
        ['shop'] = 'pdm',
    },
	['chiron'] = {
        ['name'] = 'Chiron 2021',
        ['brand'] = 'Bugatti',
        ['model'] = 'chiron',
        ['price'] = 1300000,
        ['category'] = 'Bugatti',
        ['categoryLabel'] = 'Bugatti',
        ['hash'] = `chiron`,
        ['shop'] = 'pdm',
    },
	['divo'] = {
        ['name'] = 'Divo 2021',
        ['brand'] = 'Bugatti',
        ['model'] = 'divo',
        ['price'] = 1300000,
        ['category'] = 'Bugatti',
        ['categoryLabel'] = 'Bugatti',
        ['hash'] = `divo`,
        ['shop'] = 'pdm',
    },
	['wycalt'] = {
        ['name'] = 'Atlantic Concept 2015',
        ['brand'] = 'Bugatti',
        ['model'] = 'wycalt',
        ['price'] = 1300000,
        ['category'] = 'Bugatti',
        ['categoryLabel'] = 'Bugatti',
        ['hash'] = `wycalt`,
        ['shop'] = 'pdm',
    },
	['durango18'] = {
        ['name'] = 'Durango 2018',
        ['brand'] = 'Dodge',
        ['model'] = 'durango18',
        ['price'] = 1300000,
        ['category'] = 'Dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = `durango18`,
        ['shop'] = 'pdm',
    },
	['dvgtsr'] = {
        ['name'] = 'Viper SRT 2010',
        ['brand'] = 'Dodge',
        ['model'] = 'dvgtsr',
        ['price'] = 1300000,
        ['category'] = 'Dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = `dvgtsr`,
        ['shop'] = 'pdm',
    },
	['Hellaphant'] = {
        ['name'] = 'Charger R/T 1970',
        ['brand'] = 'Dodge',
        ['model'] = 'Hellaphant',
        ['price'] = 1300000,
        ['category'] = 'Dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = `Hellaphant`,
        ['shop'] = 'pdm',
    },
	['vip8'] = {
        ['name'] = 'Viper SRT 2009',
        ['brand'] = 'Dodge',
        ['model'] = 'vip8',
        ['price'] = 1300000,
        ['category'] = 'Dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = `vip8`,
        ['shop'] = 'pdm',
    },
	['frs'] = {
        ['name'] = 'Raptor 2018',
        ['brand'] = 'Ford',
        ['model'] = 'frs',
        ['price'] = 1300000,
        ['category'] = 'Ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = `frs`,
        ['shop'] = 'pdm',
    },
	['mst302'] = {
        ['name'] = 'Mustang 302 BOSS 1963',
        ['brand'] = 'Ford',
        ['model'] = 'mst302',
        ['price'] = 1300000,
        ['category'] = 'Ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = `mst302`,
        ['shop'] = 'pdm',
    },
	['mustang'] = {
        ['name'] = 'Mustang spec3 2018',
        ['brand'] = 'Ford',
        ['model'] = 'mustang',
        ['price'] = 1300000,
        ['category'] = 'Ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = `mustang`,
        ['shop'] = 'pdm',
    },
	['mustangspec5'] = {
        ['name'] = 'Mustang spec5 2020',
        ['brand'] = 'Ford',
        ['model'] = 'mustangspec5',
        ['price'] = 1300000,
        ['category'] = 'Ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = `mustangspec5`,
        ['shop'] = 'pdm',
    },
	['rmodmustang'] = {
        ['name'] = 'Mustang GT 2020',
        ['brand'] = 'Ford',
        ['model'] = 'rmodmustang',
        ['price'] = 1300000,
        ['category'] = 'Ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = `rmodmustang`,
        ['shop'] = 'pdm',
    },
	['wildtrak'] = {
        ['name'] = 'Bronco Wild Track 2021',
        ['brand'] = 'Ford',
        ['model'] = 'wildtrak',
        ['price'] = 1300000,
        ['category'] = 'Ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = `wildtrak`,
        ['shop'] = 'pdm',
    },
	['dc5'] = {
        ['name'] = 'Integra TypeR 2002',
        ['brand'] = 'Honda',
        ['model'] = 'dc5',
        ['price'] = 1300000,
        ['category'] = 'Honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = `dc5`,
        ['shop'] = 'pdm',
    },
	['filthynsx'] = {
        ['name'] = 'NSX 2020',
        ['brand'] = 'Acura',
        ['model'] = 'filthynsx',
        ['price'] = 1300000,
        ['category'] = 'Acura',
        ['categoryLabel'] = 'Acura',
        ['hash'] = `filthynsx`,
        ['shop'] = 'pdm',
    },
	['honcrx91'] = {  --spawn code
        ['name'] = 'CRX siR 1991', -- car name
        ['brand'] = 'Honda', -- car brand
        ['model'] = 'honcrx91', -- spawncode
        ['price'] = 1300000, -- price
        ['category'] = 'Honda', -- category
        ['categoryLabel'] = 'Honda', -- Cat label
        ['hash'] = `honcrx91`, -- spawncode
        ['shop'] = 'pdm', -- shop name
    },
}
